apiVersion: v2
name: aigateway-console
description: Management console for AIGateway
type: application
version: 2.2.0
sources:
  - https://github.com/alibaba/aigateway-group/aigateway-console
appVersion: "2.2.0"
